USE [master]
GO

/****** Object:  Database [InyeccionSQL]    Script Date: 26/07/2021 18:43:21 ******/
CREATE DATABASE [InyeccionSQL] ON  PRIMARY 
( NAME = N'InyeccionSQL', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESSINES\MSSQL\DATA\InyeccionSQL.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'InyeccionSQL_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESSINES\MSSQL\DATA\InyeccionSQL_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [InyeccionSQL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [InyeccionSQL] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [InyeccionSQL] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [InyeccionSQL] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [InyeccionSQL] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [InyeccionSQL] SET ARITHABORT OFF 
GO

ALTER DATABASE [InyeccionSQL] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [InyeccionSQL] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [InyeccionSQL] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [InyeccionSQL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [InyeccionSQL] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [InyeccionSQL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [InyeccionSQL] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [InyeccionSQL] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [InyeccionSQL] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [InyeccionSQL] SET  DISABLE_BROKER 
GO

ALTER DATABASE [InyeccionSQL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [InyeccionSQL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [InyeccionSQL] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [InyeccionSQL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [InyeccionSQL] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [InyeccionSQL] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [InyeccionSQL] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [InyeccionSQL] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [InyeccionSQL] SET  MULTI_USER 
GO

ALTER DATABASE [InyeccionSQL] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [InyeccionSQL] SET DB_CHAINING OFF 
GO

ALTER DATABASE [InyeccionSQL] SET  READ_WRITE 
GO

