CREATE PROCEDURE SP_INSERTAPRODUCTO
@NOMBREPRODUCTO VARCHAR(20),
@PRECIOUNIDAD DECIMAL(20,2),
@UNIDADSTOCK INT
AS
INSERT INTO PRODUCTOS(NOMBREPRODUCTO,PRECIOUNIDAD,UNIDADSTOCK)
VALUES(@NOMBREPRODUCTO,@PRECIOUNIDAD,@UNIDADSTOCK)