
CREATE PROCEDURE  SP_MODPRODUCTO
@NOMBREPRODUCTO VARCHAR(20),
@PRECIOUNIDAD DECIMAL(20,2),
@UNIDADSTOCK INT
AS
UPDATE PRODUCTOS
SET  PRECIOUNIDAD=@PRECIOUNIDAD,UNIDADSTOCK=@UNIDADSTOCK
WHERE(NOMBREPRODUCTO=@NOMBREPRODUCTO)
