--PRACTICA UNIDAD UF1845
--1) DEVUELVE UN LISTADO CON LOS EMPLEADOS Y LOS DATOS DE LOS DEPARTAMENTOS DONDE TRABAJA CADA UNO.
SELECT *
FROM empleado INNER JOIN departamento
ON empleado.codigo = departamento.codigo;

--2)DEVUELVE UNA LISTA CON EL NOMBRE DE LOS DEPARTAMENTOS Y EL PRESUPUESTO, QUE TIENEN UN PRESUPUESTO ENTRE 100000 Y 200000 EUROS. sIN UTILIZAR EL OPERADOR between
SELECT nombre, presupuesto
from departamento
where 100000 < presupuesto AND presupuesto < 200000;

--3) Devuelve un listado donde solo aparezcan aquellos empleados que no tienen ningún departamento asociado

SELECT nombre
FROM empleado 
WHERE codigo_departamento IS NULL;

--4) DEVUELVE UN LISTADO CON EL CÓDIGO Y EL NOMBRE DEL DEPARTAMENTO, SOLAMENTE DE AQUELLOS DEPARTAMENTOS QUE TIENEN EMPLEADOS 
SELECT codigo, nombre
FROM   departamento
WHERE presupuesto > 0;

--5)Añade un nuevo empleado (procedimiento almacenado)
CREATE PROCEDURE SP_ALTAEMPLEADO
@CODIGO INT,
@NIF VARCHAR(9),
@NOMBRE VARCHAR (100),
@APELLIDO1 VARCHAR(100), 
@APELLIDO2 VARCHAR(100), 
@CODIGO_DEPARTAMENTO INT
AS
INSERT INTO empleado (CODIGO, NIF, NOMBRE, APELLIDO1, APELLIDO2, CODIGO_DEPARTAMENTO)
VALUES (@CODIGO,@NIF, @NOMBRE, @APELLIDO1,@APELLIDO2,@CODIGO_DEPARTAMENTO);

--6)CONSULTA QUE ELIMINE TODOS LOS DEPARTAMENTOS CUYO PRESUPUESTO SEA SUPERIOR A UNO QUE SE INTRODUCE POR TECLADO (PROCEDIMIENTO ALMACENADO)
CREATE PROCEDURE SP_ELIMINARDEPARTAMENTO
@CODIGO INT,
@NOMBRE VARCHAR (100),
@PRESUPUESTO DECIMAL (18,0),
@GASTOS DECIMAL (18,0)
AS
DELETE FROM departamento
WHERE codigo = @CODIGO;

EXEC SP_ELIMINARDEPARTAMENTO 1, desarrollo, 120000, 6000;