<?xml version="1.0" encoding="utf-8"?><Database Name="SonriePerlora" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=tcp:perlora.database.windows.net,1433;Initial Catalog=SonriePerlora;Persist Security Info=True;User ID=administrador" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SonriePerloraConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cliente" Member="Cliente">
    <Type Name="Cliente">
      <Column Name="ID_Cliente" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellidos" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Genero" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DNI" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Edad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Localidad" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NumPersonas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Animales" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Habitacion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="FechaInicio" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FechaFin" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PackCamp" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Dieta" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Alergias" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiversidadFuncional" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_Departamento" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Departamento_Cliente" Member="Departamento" ThisKey="ID_Departamento" OtherKey="ID_Departamento" Type="Departamento" IsForeignKey="true" />
      <Association Name="Departamento_Cliente1" Member="Departamento1" ThisKey="ID_Departamento" OtherKey="ID_Departamento" Type="Departamento" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Departamento" Member="Departamento">
    <Type Name="Departamento">
      <Column Name="ID_Departamento" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Actividad" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Departamento_Cliente" Member="Cliente" ThisKey="ID_Departamento" OtherKey="ID_Departamento" Type="Cliente" />
      <Association Name="Departamento_Cliente1" Member="Cliente1" ThisKey="ID_Departamento" OtherKey="ID_Departamento" Type="Cliente" />
      <Association Name="Departamento_Personal" Member="Personal" ThisKey="ID_Departamento" OtherKey="ID_Departamento" Type="Personal" />
    </Type>
  </Table>
  <Table Name="dbo.Nominas" Member="Nominas">
    <Type Name="Nominas">
      <Column Name="ID_Nominas" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Vacaciones" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Bajas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PrecioHora" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="PrecioHoraExtra" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="HorasTrabajadas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HorasExtra" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IRPF" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Liquidacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DireccionEmpresa" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cod_Cuenta" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Personal_Nominas" Member="Personal" ThisKey="ID_Nominas" OtherKey="ID_Personal" Type="Personal" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Personal" Member="Personal">
    <Type Name="Personal">
      <Column Name="ID_Personal" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellidos" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Genero" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DNI" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NSS" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Localidad" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cpostal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_Departamento" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TipoContrato" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Puesto" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TipoJornada" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SalarioBruto" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SalarioNeto" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="Personal_Nominas" Member="Nominas" ThisKey="ID_Personal" OtherKey="ID_Nominas" Type="Nominas" />
      <Association Name="Departamento_Personal" Member="Departamento" ThisKey="ID_Departamento" OtherKey="ID_Departamento" Type="Departamento" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Admin" Member="Admin">
    <Type Name="Admin">
      <Column Name="usuario" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pass" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tipo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>