USE [master]
GO

/****** Object:  Database [ListadoAlumnado]    Script Date: 27/07/2021 19:19:35 ******/
CREATE DATABASE [ListadoAlumnado] ON  PRIMARY 
( NAME = N'ListadoAlumnado', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESSINES\MSSQL\DATA\ListadoAlumnado.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ListadoAlumnado_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESSINES\MSSQL\DATA\ListadoAlumnado_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ListadoAlumnado].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ListadoAlumnado] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ListadoAlumnado] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ListadoAlumnado] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ListadoAlumnado] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ListadoAlumnado] SET ARITHABORT OFF 
GO

ALTER DATABASE [ListadoAlumnado] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ListadoAlumnado] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ListadoAlumnado] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ListadoAlumnado] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ListadoAlumnado] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ListadoAlumnado] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ListadoAlumnado] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ListadoAlumnado] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ListadoAlumnado] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ListadoAlumnado] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ListadoAlumnado] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ListadoAlumnado] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ListadoAlumnado] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ListadoAlumnado] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ListadoAlumnado] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ListadoAlumnado] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ListadoAlumnado] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ListadoAlumnado] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ListadoAlumnado] SET  MULTI_USER 
GO

ALTER DATABASE [ListadoAlumnado] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ListadoAlumnado] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ListadoAlumnado] SET  READ_WRITE 
GO

