USE [master]
GO

/****** Object:  Database [FormuLinQ]    Script Date: 02/08/2021 17:58:18 ******/
CREATE DATABASE [FormuLinQ] ON  PRIMARY 
( NAME = N'FormuLinQ', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESSINES\MSSQL\DATA\FormuLinQ.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'FormuLinQ_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESSINES\MSSQL\DATA\FormuLinQ_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FormuLinQ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FormuLinQ] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FormuLinQ] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FormuLinQ] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FormuLinQ] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FormuLinQ] SET ARITHABORT OFF 
GO

ALTER DATABASE [FormuLinQ] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FormuLinQ] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FormuLinQ] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FormuLinQ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FormuLinQ] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FormuLinQ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FormuLinQ] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FormuLinQ] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FormuLinQ] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FormuLinQ] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FormuLinQ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FormuLinQ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FormuLinQ] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FormuLinQ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FormuLinQ] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FormuLinQ] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FormuLinQ] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FormuLinQ] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FormuLinQ] SET  MULTI_USER 
GO

ALTER DATABASE [FormuLinQ] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FormuLinQ] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FormuLinQ] SET  READ_WRITE 
GO

