--PARTE 2. cONSULTAS

--1 CONSULTAR LAS CUENTAS DE LOS CLINENTES CUYO aPELLIDO EMPIECE POR A
SELECT B.APELLIDOS + ',' + B.NOMBRES AS CLIENTE, A.IDCUENTA, A.SALDO
FROM CUENTA A INNER JOIN CLIENTE B
ON A.IDCLIENTE = B.IDCLIENTE
WHERE APELLIDOS LIKE 'A%'

--2 CONSULTAR TODOS LOS MOVIMIENTOS DE LAS CUENTAS EN DIVISA EURO DEL CLIENTE CUYOS aPELLIDOS ES PEREZ

SELECT A.IDCUENTA, C.FECHA, C.MONTO, TIPO = CASE C.TIPO WHEN 'D' THEN 'DEPOSITO' WHEN 'R'THEN 'RETIRO' WHEN 'T' THEN 'TRANSFERENCIA' END
FROM CUENTA A INNER JOIN CLIENTE B 
ON A.IDCLIENTE = B.IDCLIENTE INNER JOIN MOVIMIENTO C 
ON A.IDCUENTA = C.IDCUENTA
WHERE A.DIVISA ='EUROS'AND B.APELLIDOS = 'PEREZ'
ORDER BY C.FECHA DESC

--3 CONSULTAR TODOS LOS MOVIMIENTOS DE LAS CUENTAS DEL CLIENTE pEREZ EN EUROS (AUNQUE TENGA CUENTAS EN OTRS DIVISAS) ORDENADAS POR EL NÚMERO DE CUENTA
SELECT C.NOMBRES, C.APELLIDOS, CU.IDCUENTA, CU.SALDO, CU.DIVISA, M.IDMOVIMIENTO, M.MONTO,M.TIPO
FROM CLIENTE C INNER JOIN CUENTA CU
ON C.IDCLIENTE = CU.IDCLIENTE 
INNER JOIN MOVIMIENTO M
ON CU.IDCUENTA = M.IDCUENTA
WHERE C.APELLIDOS = 'PEREZ'
ORDER BY CU.IDCUENTA


--4 CONSULTAR LOS MOVIMIENTOS DE PEREZ Y LOS DE RODRIGUEZ.

SELECT A.IDCUENTA, C.FECHA, C.MONTO, C.TIPO
FROM CUENTA A INNER JOIN CLIENTE B 
ON A.IDCLIENTE = B.IDCLIENTE
INNER JOIN MOVIMIENTO C 
ON A.IDCUENTA = A.IDCUENTA
WHERE C.TIPO = 'DEPOSITO' AND B.APELLIDOS = 'PEREZ' OR C.TIPO = 'TRANSACCIONES' AND B.APELLIDOS = 'RODRIGUEZ'
ORDER BY C.FECHA DESC