

CREATE TABLE CLIENTE(
IDCLIENTE VARCHAR(5) NOT NULL PRIMARY KEY,
APELLIDOS VARCHAR(30),
NOMBRES VARCHAR (30)
)

create table CUENTA(
IDCLIENTE VARCHAR(5),
IDCUENTA varchar(5) NOT NULL  PRIMARY KEY,
SALDO FLOAT,
DIVISA VARCHAR(20)
CONSTRAINT FK_IDCLIENTE FOREIGN KEY  (IDCLIENTE)	REFERENCES CLIENTE(IDCLIENTE)
)


create table MOVIMIENTO(
IDCUENTA varchar (5),
IDMOVIMIENTO VARCHAR(5) NOT NULL PRIMARY KEY,
TIPO VARCHAR(20),
MONTO FLOAT,
FECHA DATE
CONSTRAINT FK_IDCUENTA FOREIGN KEY  (IDCUENTA)	REFERENCES CUENTA(IDCUENTA)
)
